# 1. Import Libraries

In [1]:
%pip install feature-engine

Requirement already satisfied: feature-engine in /usr/local/lib/python3.13/dist-packages (1.9.4)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.13/dist-packages (from feature-engine) (2.1.3)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from feature-engine) (2.2.3)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from feature-engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from feature-engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.13/dist-packages (from feature-engine) (0.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature-engine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature-engine) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature-engine) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature-engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature-engine) (1.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature-engine) (26.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature-engine) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature-engine) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature-engine) (2.25.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature-engine) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature-engine) (2.4.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.4.0->feature-engine) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature-engine) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import pickle

# 2. Load Model

In [3]:
# Load model Random Forest
with open('P1M2_Angelina_Yessyca.pkl', 'rb') as file_1:
  model_rf = pickle.load(file_1)

# Load Winsorizer
with open('windsoriser.pkl', 'rb') as file_2:
  windsoriser = pickle.load(file_2)

# Load Label Encoder
with open('label_encoder.pkl', 'rb') as file_3:
  label_encoder = pickle.load(file_3)

# 3. Membuat Data Inference

In [4]:
# Membuat 1 data baru
data_inf = {
    'age' : 39,
    'job' : 'entrepreneur',
    'marital' : 'single',
    'education' : 'basic.9y',
    'default' : 'no',
    'housing' : 'yes',
    'loan' : 'no',
    'contact' : 'cellular',
    'month' : 'dec',
    'day_of_week' : 'fri',
    'duration' : 390,
    'campaign' : 3,
    'pdays' : 999,
    'previous' : 0,
    'poutcome' : 'nonexistent',
    'emp.var.rate' : -1.8,
    'cons.price.idx' : 92.893,
    'cons.conf.idx' : -46.2,
    'euribor3m' : 1.313,
    'nr.employed' : 5099.1
}

# Mengubah dictionary menjadi DataFrame
data_inf = pd.DataFrame([data_inf])
data_inf

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,39,entrepreneur,single,basic.9y,no,yes,no,cellular,dec,fri,390,3,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1

# 4. Preprocessing Data Inference

In [5]:
# Mengubah nilai 999 pada pdays menjadi missing value
data_inf['pdays'] = data_inf['pdays'].replace(999, np.nan)

# Menangani outlier menggunakan winsoriser yang sudah dilatih
data_inf = windsoriser.transform(data_inf)

# Menghapus fitur duration
data_inf = data_inf.drop(['duration'], axis = 1)
data_inf

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,39,entrepreneur,single,basic.9y,no,yes,no,cellular,dec,fri,3,NaN,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1

# 5. Melakukan Prediksi

In [6]:
# Melakukan prediksi
y_pred_inf = model_rf.predict(data_inf)
y_pred_inf

array([0])

# 6. Kesimpulan

Setelah dilakukan penambahan 1 data baru ke dalam model Random Forest didapatkan hasil bahwa pada data baru ini menghasilkan prediksi 0 yang berarti bahwa calon nasabah tersebut tidak akan berlangganan deposito (no).